version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "security(actions): "
  - package-ecosystem: "gomod" 
    directory: "/" 
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "security(go): "
  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "security(docker): "
