version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -tags=viper_bind_struct
    tags:
      - viper_bind_struct
    ldflags:
      - -s -w -X {{.Env.PKG}}/internal.tilegroxyVersion={{.Env.VERSION}} -X {{.Env.PKG}}/internal.tilegroxyBuildRef={{.Env.REF}} -X {{.Env.PKG}}/internal.tilegroxyBuildDate={{.Env.DATE}}
archives:
  - builds_info:
      mode: 0744
    format_overrides:
      - goos: windows
        format: zip
changelog:
  use: github-native
release:
  github:
    owner: michad
    name: tilegroxy
  draft: true
  replace_existing_draft: true
  extra_files:
    - glob: ./LICENSE