server:
  production: false
  port: 8081
error:
  mode: image+header
logging:
  mainlog:
    format: json
    level: debug
  accesslog:
    format: combined
authentication:
  name: jwt
  algorithm: HS256
  verificationKey: askfasklfj
  CacheSize: 100
# cache:
#   name: multi
#   tiers:
#     -
#       name: memory
#       MaxSize: 1000
#       Ttl: 1000
#     -
#       name: disk
#       path: "./disK_tile_cache"
#     -
#       name: disk
#       path: "./disK_tile_cache2"
# cache:
#   name: s3
#   bucket: tilegroxy-directory-cache--use1-az6--x-s3
#   endpoint: "https://s3express-use1-az6.us-east-1.amazonaws.com"
#   storageclass: EXPRESS_ONEZONE
#   # bucket: tilegroxy-demo-cache
#   region: us-east-1
#   profile: tilegroxy
cache:
  name: redis
  mode: standalone
layers:
  -
    id: test
    provider:
      name: url template
      template: http://example.com/?bbox=$xmin,$ymin,$xmax,$ymax
  -
    id: test2
    provider:
      name: url template
      template: http://example.com/?bbox=$xmin,$ymin,$xmax,$ymax
  -
    id: osm
    provider:
        name: proxy
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png