server:
  production: false
  port: 8081
logging:
  mainlog:
    format: json
    level: debug
  accesslog:
    format: combined
# authentication:
#   name: jwt
#   algorithm: HS256
#   verificationKey: askfasklfj
#   CacheSize: 100
cache:
  name: multi
  tiers:
    -
      name: memory
      MaxSize: 1000
      Ttl: 1000
    -
      name: disk
      path: "./disK_tile_cache"
    -
      name: disk
      path: "./disK_tile_cache2"
layers:
  -
    id: test
    provider:
      name: url template
      template: http://example.com/?bbox=$xmin,$ymin,$xmax,$ymax
  -
    id: test2
    provider:
      name: url template
      template: http://example.com/?bbox=$xmin,$ymin,$xmax,$ymax
  -
    id: osm
    provider:
        name: proxy
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png