= Configuration

Tilegroxy is heavily configuration driven. This document describes the various configuration options available. link:../examples/configurations/[Complete examples are available here.]

Some configuration sections (<<authentication,authentication>>, <<provider,provider>>, <<cache,cache>>, and <<secret,secret>>) support selecting different methods of operation that change the full list of parameters available. For example,  a "proxy" provider requires a `url` parameter to get a map tile from another server while a "static" provider takes in a `image` to return for every request. You select these operating modes using a parameter called `name`. Since these entities are too dynamic to have fixed environment variables and frequently may require a secret to operate, any string parameters can be made to use an environment variable by specifying a value in the format of `env.ENV_VAR_NAME`.  You can also use an external secret store <<secret,if configured>> by specifying a value in the format `secret.SECRET_NAME`

Configuration key names are case-insensitive unless indicated otherwise. Names are always lower case.

Some parameters can be specified by environment variables which must be upper case. Environment variables override config parameters which override default values.

The following is the top-level configuration structure. All top-level keys are optional besides layers:

____
xref:configuration/server.adoc[server]:  ... +
xref:configuration/client.adoc[client]:  ... +
xref:configuration/log.adoc[logging]:  ... +
xref:configuration/telemetry.adoc[telemetry]: ... +
xref:configuration/error.adoc[error]:  ... +
xref:configuration/secret/index.adoc[secret]: ... +
xref:configuration/authentication/index.adoc[authentication]:  ... +
xref:configuration/cache/index.adoc[cache]:  ... +
xref:configuration/datastores/index.adoc[datastores]: +
   - ... +
xref:configuration/layer.adoc[layers]:  +
   - ... +
____