= Layer

A layer represents a distinct mapping layer as would be displayed in a typical web map application.  Each layer can be accessed independently from other map layers. The main thing that needs to be configured for a layer is the provider described below.

The URLs of incoming requests follow a format like: `+/tiles/{layerName}/{z}/{x}/{y}+` the layer name can be one of two things: 1) the ID of the layer or 2) A string that matches a pattern.  A pattern should include non-subsequent placeholder values wrapped in curly braces. Those placeholder values can be used in certain providers, such as the Proxy provider where they can be forwarded along to the upstream map layer. To understand how you can utilize patterns, see the link:../examples/configurations/noaa_post_storm.yml[NOAA Post-Storm example]

When using a pattern you can include https://regex101.com/[Regular Expressions] to validate the values that match against the placeholder.

Configuration options:

|===
| Parameter | Type | Required | Default | Description

| id
| string
| Yes
| None
| A url-safe identifier of the layer. Primarily used as the default path for incoming tile web requests

| pattern
| string
| No
| id
| A url-safe pattern with non-subsequent placeholders

| paramValidator
| map[string]string
| No
| None
| A mapping of regular expressions to use to validate the values that match against the placeholders. The regular expressions must match the full value. Specify a key of "*" to apply it to all values

| provider
| Provider
| Yes
| None
| See below

| client
| Client
| No
| None
| A Client configuration to use for this layer specifically that overrides the Client from the top-level of the configuration. See below for Client schema

| skipcache
| bool
| No
| false
| If true, skip reading and writing to cache
|===

Example:

----
layer:
  id: my_layer
  pattern: my_{name}_{version}
  paramValidator:
    "*": "^[a-zA-Z0-9]+$"
    "version": "v[0-9]{1,3}"
  skipCache: true
  client:
    userAgent: my_app/1.0
  provider:
    ...
----