= Disks

Stores the cache entries as files in a location on the filesystem. 

Tilegroxy doesn't form clusters so a high-availability deployment with this cache pointing to a local filesystem will lead to inconsistent behaviour.

Files are stored in a flat structure inside the specified directory. No automatic cleanup process is included inside of `tilegroxy` itself. It is recommended you use an external job to avoid running out of disk space. 

Filenames are derived from the layer name and tile coordinates, for example `mylayer_1_2_3`. Layer names are sanitized by replacing potentially dangerous characters with an underscore. This can lead to exotically named layers colliding. Be cognizant of that risk when using this cache.

Cache entries are written to a temporary file (in the same directory) and then renamed, so an interrupted write won't leave partial files behind. The temp files should get automatically removed, but if you see any old files ending with `.tmp`, feel free to clean them up.

Name should be "disk"

Configuration options:

[cols="1,3,1,1,1"]
|===
| Parameter  | Description | Type | Required | Default

| path
| The absolute path to the directory to store cache entries within. Directory (and tree) will be created if it does not already exist
| string
| Yes
| None

| filemode
| A https://pkg.go.dev/io/fs#FileMode[Go filemode] as an integer to use for all created files/directories. This might change in the future to support a more conventional unix permission notation
| uint32
| No
| 0777
|===

Example:

[,json]
----
"cache": {
  "name": "disk",
  "path": "./disk_tile_cache"
}
----




