= Cache

The cache configuration defines the datastores where tiles should be stored/retrieved. We recommended you use a `multi`-tiered cache with a smaller, faster "near" cache first followed by a larger, slower "far" cache.

There is no universal mechanism for expiring cache entries. Some cache options include built-in mechanisms for applying an TTL and maximum size, however some require an external cleanup mechanism if desired. Be mindful of this as some options may incur their own costs if allowed to grow unchecked. To delete entries covering a specific area, use xref:commands/seed.adoc[the seed command] with `--purge`.

When specifying a cache ensure you include the `name` parameter.

== Overridable caches

Layer configurations have the ability to specify a `cache` parameter that overrides the default cache configuration.  The top-level `cache` definition can be an array for specifying multiple distinct caches.  This is different from the `multi` cache mentioned above. The `multi` cache allows combining multiple physical caches into a single cache config, but specifying an array under `cache` directly specifies multiple distinct cache configs.

Cache configurations are referred to by their `id` parameter, which defaults to the cache's `name`. If you have multiple caches of the same kind, then `id` is required.

The first cache in the list will be used as the default cache. Any layers you want to use a different cache config should include `cache: SOME_ID` inside the layer definition. Any cache configuration can be referred to by ID in this way, including a cache that's defined within another cache.  Said another way, if you have a `multi` cache containing a `disk` cache and a `memcached` cache, a layer can be configured to refer to just the `memcached` cache.

If you don't want to use the first cache in the list as your default, you can specify a `defaultcache` parameter at the very top-level of your configuration.  This parameter takes the ID of the cache to use as your default. 

Be aware: there is no deduplication of cache configurations. That means if you have two identical `memory` caches defined, each will be a totally separate cache with their own memory allocations and capacity. This goes for all other cache types. If you need to define a cache multiple times (for example to be used under different `multi`, `ttl`, or `tenant` setups) it's recommended you utilize xref:configuration/datastores/index.adoc[datastores].

=== Example

[,yaml]
----
cache:
  - id: tenanted
    name: tenant
    cache:
      name: multi
      tiers:
        - name: memory
          datastore: tiles
        - name: s3
          bucket: my-tile-cache
  - name: none

defaultcache: multi

layers:
  - id: public
    provider:
      name: proxy
      url: https://example.com/{z}/{x}/{y}.png
  - id: per-user
    cache: tenanted
    provider:
      name: proxy
      url: https://example.com/private/{z}/{x}/{y}.png
  - id: uncached
    cache: none
    provider:
      name: proxy
      url: https://example.com/live/{z}/{x}/{y}.png
datastores: ...
----

In this example, the `public` layer (and all layers by default) will use a `multi` cache that caches in-memory first and then falls back on an S3 bucket. 

The `per-user` layer overrides the cache to use the `tenanted` cache, which means it will still use that same cache methodology, but the entries in the cache will be segregated by tenant.

The `uncached` layer meanwhile won't be cached as it will use the no-op `none` cache.  Note, alternatively you could use the `skipcache` parameter to avoid needing to explicitly define a `none` cache at the top level.