= AWS Secrets Manager

This secret source utilizes the https://aws.amazon.com/secrets-manager/[AWS Secrets Manager] service.

This source includes a cache for values. This avoids repeatedly querying for the same value e.g. if it's used by multiple providers.  Currently secrets are only pulled at once at startup, however in the future this might be changed to re-pull periodically or upon configuration changes. Therefore it is advised to think through how often your secrets might rotate when configuring the TTL value, even though currently it only need to be a small value to span the initial start-up of the application.

Secrets Manager places secrets inside a JSON structure if configured through the console.  To support that keys should be in the structure of `id:key` with `id` being the ID of the secret as a whole and `key` being the key from the JSON Object stored in the secret.  If the secret isn't JSON then you only need to supply the `id` by itself.  You can override the separator used to be any value rather than a colon (`:`).

This supports the standard means of authenticating with AWS.  Ensure your user/role includes permission both to retrieve the secrets as well as permission to use the relevant KMS key to decrypt it.

Name should be "awssecretsmanager"

Configuration options:

|===
| Parameter | Type | Required | Default | Description

| separator
| string
| No
| :
| How to separate the Id of the secret from the JSON key in the secret name as a whole

| ttl
| int
| No
| 1 hour
| How long to cache secrets in seconds. Cache disabled if less than 0.

| region
| string
| No
| None
| The AWS region containing the bucket. Required if region is not specified via other means. Consult https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints[AWS documentation] for possible values

| access
| string
| No
| None
| The AWS Access Key ID to authenticate with. This is not recommended; it is offered as a fallback authentication method only. Consult https://docs.aws.amazon.com/cli/v1/userguide/cli-chap-authentication.html[AWS documentation] for better options

| secret
| string
| No
| None
| The AWS Secret Key to authenticate with. This is not recommended; it is offered as a fallback authentication method only. Consult https://docs.aws.amazon.com/cli/v1/userguide/cli-chap-authentication.html[AWS documentation] for better options

| profile
| string
| No
| None
| The profile to use to authenticate against the AWS API. Consult https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html#file-format-profile[AWS documentation for specifics]
|===