= GCP Secret Manager

This secret source utilizes the https://cloud.google.com/security/products/secret-manager[GCP Secret Manager] service.

This source includes a cache for values. This avoids repeatedly querying for the same value e.g. if it's used by multiple providers.  Currently secrets are only pulled at once at startup, however in the future this might be changed to re-pull periodically or upon configuration changes. Therefore it is advised to think through how often your secrets might rotate when configuring the TTL value, even though currently it only need to be a small value to span the initial start-up of the application.

Secret Manager stores each secret as a series of versions rather than a single JSON document. To reference a specific version instead of the default, keys should be in the structure of `id:key:version` with `id` being the name of the secret, `key` being an optional key to pull out of the secret payload if it's a JSON Object, and `version` being the numbered version or `latest`. If you only need the default version you can supply `id` by itself or `id:key` to pull a key out of a JSON payload. You can override the separator used to be any value rather than a colon (`:`).

This supports the standard means of authenticating with GCP, defaulting to https://cloud.google.com/docs/authentication/application-default-credentials[Application Default Credentials]. Ensure the identity used includes the `roles/secretmanager.secretAccessor` role for the secrets it needs to read.

Name should be "gcpsecretmanager"

Configuration options:

[cols="1,3,1,1,1"]
|===
| Parameter | Description | Type | Required | Default

| project
| The GCP project id containing the secrets
| string
| Yes
| None

| separator
| How to separate the Id of the secret from the JSON key and version in the secret name as a whole
| string
| No
| :

| version
| The version of a secret to use when a key doesn't specify one explicitly
| string
| No
| latest

| ttl
| How long to cache secrets in seconds. Cache disabled if less than 0.
| int
| No
| 1 hour

| credentialsfile
| Path to a service account JSON key file to authenticate with. Consult https://cloud.google.com/docs/authentication/application-default-credentials[GCP documentation] for better options
| string
| No
| None

| endpoint
| Overrides the Secret Manager API endpoint. Intended for testing against an emulator, not for production use
| string
| No
| None
|===
