= Reloading Configuration

Tilegroxy supports limited hot-loading of configuration without a restart. Configuration changes that affect the core functionality of the service, including changes to the HTTP server, do not support reloading and instead require a restart of the executable.  Reloading is only supported when running the `serve` command and must be explicitly enabled via the CLI parameter `--hot-reloading`

Reloading occurs automatically within a few seconds of configuration changing on the filesystem.  It is not supported for remote providers such as etcd.  When reloading the configuration, the new configuration is stored side-by-side with the previous configuration and swapped atomically. The exact timing of that change cannot be controlled but should occur within several seconds of configuration being updated, depending on the size of your configuration.  Requests that are in-flight will continue operating against the old configuration while new requests coming in will use the new configuration.

When reloading occurs new connections will be established for configured xref:configuration/datastores/index.adoc[datastores]. This will lead to the number of connections to the databases to increase. Connections are not explicitly killed and instead rely on idle timeouts and garbage collection to occur for them to be cleaned up. If configuration changes repeatedly occur in a short period this can lead to a large number of connections being established. Consider relying on traditional deployment methodologies if you're sensitive to the number of active DB connections.

The following sections can be reloaded:

* xref:configuration/secret/index.adoc[secret]
* xref:configuration/client.adoc[client]
* xref:configuration/authentication/index.adoc[authentication]
* xref:configuration/cache/index.adoc[cache]
* xref:configuration/datastores/index.adoc[datastores]
* xref:configuration/layer.adoc[layers]

The following sections can be partially reloaded:

* xref:configuration/error.adoc[error]
** Overall error handling mode will not be changed but the error messages returned due to issues specific to individual layers will


