Server:
    BindHost: 0.0.0.0
    Gzip: true
    Port: 8443
    Production: true
    Headers:
        Access-Control-Allow-Origin: "*"
    Timeout: 30
    Encrypt:
      Domain: dev.local.io
      HttpPort: 8080
      #Actually the default value. Try setting to 1.3 for latest and greatest
      MinTLS: 1.2
      #Disable all weak TLS 1.2 ciphers
      DisableCiphers: 
        - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
        - TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
      # Certificate: certs/my-certificate.crt
      # Keyfile: certs/my-key.key
Logging:
    Access:
        Console: false
        Format: combined
        Path: "my-access.log"
    Main:
        Console: true
        Format: json
        Level: error
        Path: "my-main.log"
# Authentication:
#   name: jwt
#   algorithm: HS256
#   key: some_secret_key
Client:
    UnknownLength: false
    ContentTypes:
        - image/png
        - image/jpeg
        - image/webp
    StatusCodes:
        - 200
        - 201
    MaxLength: 100000000
    UserAgent: company/1.0
error:
    Mode: image
cache:
  name: multi
  tiers:
    - name: memory
      maxsize: 1000
      ttl: 1000
    - name: disk
      path: "./disk_tile_cache"
layers: 
  - id: osm
    provider:
        name: proxy
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
