= Migrating from tilestache

An important difference between tilegroxy and tilestache is that tilegroxy can only be run as a standalone executable rather than running as a module in another webserver.  However tilegroxy, like tilestache, can also link:./extensibility.md#using-tilegroxy-as-a-library[be used as a library] if you wish to build applications extending it.

The configuration in tilegroxy is meant to be highly compatible with the configuration of tilestache, however there are significant differences. The tilegroxy configuration supports a variety of options that are not available in tilestache and while we try to keep most parameters optional and have sane and safe defaults, it is highly advised you familiarize yourself with the various options documented above.

The following are the known incompatibilities with tilestache configurations:

+++<ul><li>+++
 Unsupported providers:
+++</li><ul style="margin-bottom:0"><li>+++
  Mapnik
+++</li><li>+++
  Vector
+++</li><li>+++
  MBTiles
+++</li><li>+++
  Mapnik Grid
+++</li><li>+++
  Goodies providers
+++</li></ul><li>+++
 Unsupported caches:
+++</li><ul style="margin-bottom:0"><li>+++
  LimitedDisk
+++</li></ul><li>+++
 "Names" are always in all lowercase
+++</li><li>+++
 Configuration keys are case insensitive and have no spaces
+++</li><li>+++
 Configuring projections is currently unsupported
+++</li><li>+++
 Cache contents are not guaranteed to be transferrable
+++</li><li>+++
 Layers:
+++</li><ul style="margin-bottom:0"><li>+++
  Layers are supplied as a flat array of layer objects with an `id` parameter for the URL-safe layer name instead of them being supplied as an Object with the id being a key.
+++</li><li>+++
  Most parameters unavailable. Some can be configured via the `Client` configuration and others will be added in future versions.
+++</li><li>+++
  The `write cache` parameter is replaced with `skipcache` with inverted value
+++</li><li>+++
  No `bounds` parameter - instead use the `fallback` provider but note it applies on a per-tile level only (not per-pixel)
+++</li><li>+++
  No `pixel effects` parameter - instead use the `effect` provider
+++</li></ul><li>+++
 URL Template provider:
+++</li><ul style="margin-bottom:0"><li>+++
  For the most part you should use the Proxy provider instead but URL Template is available for compatibility
+++</li><li>+++
  No `referer` parameter - instead specify the referer header via the `Client` configuration
+++</li><li>+++
  No `timeout` parameter - instead specify the timeout via the `Client` configuration
+++</li><li>+++
  No `source projection` parameter - Might be added in the future
+++</li></ul><li>+++
 Sandwich provider:
+++</li><ul style="margin-bottom:0"><li>+++
  No direct equivalent to the sandwich provider is available but most if not all functionality is available by combining Blend and Static providers
+++</li></ul><li>+++
 Proxy provider:
+++</li><ul style="margin-bottom:0"><li>+++
  No `provider` parameter
+++</li><li>+++
  No `timeout` parameter - instead specify the timeout via the `Client` configuration
+++</li></ul><li>+++
 Test cache:
+++</li><ul style="margin-bottom:0"><li>+++
  It's recommended but not required to change the `name` to "none" instead of "test"
+++</li><li>+++
  No 'verbose' parameter - Instead use the `Logging` configuration to turn on debug logging if needed
+++</li></ul><li>+++
 Disk cache:
+++</li><ul style="margin-bottom:0"><li>+++
  No `umode` parameter - Instead use `filemode` with Go numerics instead of unix numerics. Might be added in the future
+++</li><li>+++
  No `dirs` parameter - Files are currently stored in a flat structure rather than creating separate directories
+++</li><li>+++
  No `gzip` parameter - Might be added in the future
+++</li><li>+++
  The `path` parameter must be supplied as a file path, not a URI
+++</li></ul><li>+++
 Memcache cache:
+++</li><ul style="margin-bottom:0"><li>+++
  No `revision` parameter - Put the revision inside the key prefix
+++</li><li>+++
  The `key prefix` parameter is replaced with `keyprefix`
+++</li><li>+++
  The `servers` array is now an array of objects containing `host` and `port` instead of an array of strings with those combined
+++</li></ul><li>+++
 Redis cache:
+++</li><ul style="margin-bottom:0"><li>+++
  Supports a wider variety of configuration options. It's recommended but not required that you consider utilizing a Cluster or Ring deployment if you previously used a single server.
+++</li><li>+++
  The `key prefix` parameter is replaced with `keyprefix`
+++</li></ul><li>+++
 S3 cache:
+++</li><ul style="margin-bottom:0"><li>+++
  No `use_locks` parameter - Caches are currently lockless
+++</li><li>+++
  No `reduced_redundancy` parameter - Instead use the more flexible `storageclass` parameter with the "REDUCED_REDUNDANCY" option
+++</li><li>+++
  While supported, it's recommended you don't use the `access` and `secret` parameters. All standard methods of supplying AWS credentials are supported.
+++</li></ul></ul>+++
