name: Coverage
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Update coverage badge
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false 
          fetch-depth: 0 
      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
      - name: Run Test
        run: |
          make cover
      - name: Go Coverage Badge  
        uses: tj-actions/coverage-badge-go@84540b9f82b4f569ac9f248cf6f2893ac3cc4791 # v2.4.2
        with:
          filename: coveragef.out
      - name: Commit changes
        env:
          REF: ${{ github.head_ref || github.ref_name }}
        run: |
          git checkout $REF
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: Updated coverage badge."
      - name: Push changes
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # v0.8.0
        with:
          github_token: ${{ github.token }}
          branch: badge-update