name: Security Scans
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 8 * * 2'
permissions:
  contents: read
jobs:
  ossf:
    name: OSSF Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "Run analysis"
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: ${{ github.event_name != 'pull_request' }}
      - name: "Upload artifact"
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: "Upload to code-scanning"
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@bc0b696b4103f5fe60f15749af68a046868d511a # v3.28.5
        with:
          sarif_file: results.sarif
  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["go"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Initialize CodeQL
        uses: github/codeql-action/init@bc0b696b4103f5fe60f15749af68a046868d511a # v3.28.5
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@bc0b696b4103f5fe60f15749af68a046868d511a # v3.28.5
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@bc0b696b4103f5fe60f15749af68a046868d511a # v3.28.5
        with:
          category: "/language:${{matrix.language}}"

  govulncheck:
    name: Run govulncheck
    permissions:
      contents: read
      security-events: write 
    runs-on: ubuntu-latest
    steps:
    - id: govulncheck
      uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
      with:
          go-version-input: 1.25.8
          go-package: ./...
          output-format: sarif
          output-file: govuln.sarif
    - name: Post-process sarif files
      run : |
        if [ "$(/usr/bin/jq '.runs[].results' < govuln.sarif)" = "null" ]; then 
          /usr/bin/jq '.runs[] += {"results":[]}' < govuln.sarif > govuln2.sarif
        else
          cp govuln.sarif govuln2.sarif
        fi
        /usr/bin/jq '.runs[]?.tool.driver.rules[]?.properties.tags |= unique' < govuln2.sarif > govuln3.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@bc0b696b4103f5fe60f15749af68a046868d511a # v3.28.5
      with:
        sarif_file: govuln3.sarif
  gosec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write 
    env:
      GO111MODULE: on
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Run Gosec Security Scanner
        uses: securego/gosec@4a3bd8af174872c778439083ded7adbf3747e770 # v2.26.1
        with:
          args: '-no-fail -exclude=G504 -fmt sarif -out results.sarif ./...'
      - name: Upload SARIF file
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@bc0b696b4103f5fe60f15749af68a046868d511a # v3.28.5
        with:
          sarif_file: results.sarif
