name: Snyk Container

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  schedule:
    - cron: '18 8 * * 2'

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Build a Docker image
      run: docker build -t michad/tilegroxy .
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@d406fd286b663eb8c6f8adcced4f7bcd199c0a3f
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: michad/tilegroxy
        args: --file=Dockerfile
      # Snyk sometimes generates invalid severity scores that tank the upload step. And they're insistent on not fixing the bug. So we need to post-process it to avoid build failures
      # See https://github.com/github/codeql-action/issues/2187 for more context.
    - name: Post-process sarif output
      run: |
        sed -i 's/"security-severity": null/"security-severity": "0"/g' snyk.sarif
        sed -i 's/"security-severity": "null"/"security-severity": "0"/g' snyk.sarif
        sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3.25.8
      with:
        sarif_file: snyk.sarif
